### ISSUE TITLE
shine error

### ISSUE THREAD

**Issue by jeroenooms** [hadley/lineprof#16]
Trying to profile `jsonlite`, but shine is throwing an error. Does `focus` support S4 methods?

	> library(jsonlite)
	> library(lineprof)
	> lineprof(toJSON(iris))
	Reducing depth to 2 (from 32)
	   time  alloc release   dups                   ref           src
	1 0.086 73.956  72.116 135256 c("toJSON", "asJSON") toJSON/asJSON
	> lp <- lineprof(toJSON(iris))
	> shine(lp)
	Loading required package: shiny
	Loading required package: shinySlickgrid
	Shiny URLs starting with /lineprof will mapped to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/lineprof/www
	Shiny URLs starting with /slickgrid will mapped to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/shinySlickgrid/slickgrid

	Listening on port 5740
	Navigating to c("toJSON", "asJSON")
	Navigating to c("asJSON", "standardGeneric")
	Navigating to c("standardGeneric", "asJSON")
	Navigating to c("asJSON", ".local")
	Error in rowsum.data.frame(prof[c("time", "alloc", "release", "dups")],  : 
	  incorrect length for 'group'

**Comment by hadley** [comment]
Please use https://github.com/rstudio/profvis instead
