### ISSUE TITLE
Focus examples broken

### ISSUE THREAD

**Issue by jeroenooms** [hadley/lineprof#24]
> (x <- lineprof(parse_prof(find_ex("read-delim.prof"))))
	Reducing depth to 2 (from 14)
	   time  alloc release  dups                                ref                        src
	1 0.005  6.139       0  4046   c("parse_prof", "as.data.frame") parse_prof/as.data.frame  
	2 0.001  0.716       0   671 c("parse_prof", "str_replace_all") parse_prof/str_replace_all
	3 0.064 69.476       0 71916          c("parse_prof", "lapply") parse_prof/lapply         
	4 0.001  0.000       0  1332      c("parse_prof", "auto_focus") parse_prof/auto_focus     

	> # Zoom into line 38
	> (x1 <- focus(x, ref = "parse.r#38"))
	[1] time    alloc   release dups    ref     src    
	<0 rows> (or 0-length row.names)
	Warning message:
	In max(vapply(x$ref, nrow, integer(1))) :
	  no non-missing arguments to max; returning -Inf

	> # Zoom into the lapply
	> (x2 <- focus(x1, f = c("lapply", "FUN")))
	[1] time    alloc   release dups    ref     src    
	<0 rows> (or 0-length row.names)
	Warning message:
	In max(vapply(x$ref, nrow, integer(1))) :
	  no non-missing arguments to max; returning -Inf

	> align(x2)
	Error in if (is.na(path)) { : argument is of length zero

	> # Zoom into line 21
	> (x3 <- focus(x2, ref = "parse-ref.r#21"))
	[1] time    alloc   release dups    ref     src    
	<0 rows> (or 0-length row.names)
	Warning message:
	In max(vapply(x$ref, nrow, integer(1))) :
	  no non-missing arguments to max; returning -Inf

**Comment by hadley** [comment]
Please use https://github.com/rstudio/profvis instead
