### ISSUE TITLE
Truncated header row

### ISSUE THREAD

**Issue by fdetsch** [hadley/lineprof#34]
Following [Hadley's tutorial on code optimization](http://adv-r.had.co.nz/Profiling.html), I found that the header row was clipped off in RStudio when calling `shine(l)` (see below image). This also occurred when trying to open the **shiny** GUI in an external browser. Here is my code which is based on sample data from the **remote** package. Any suggestions to fix this?

```{r sample_code, eval = FALSE}
## required packages
library(remote)
library(lineprof)

## sample data
data("vdendool")

## code performance
l <- lineprof(denoise(vdendool, expl.var = 0.8))
shine(l)
```

![truncated_header](http://i.imgur.com/tWOF7J6.png)

**Comment by hadley** [comment]
I just noticed that too - it's probably related to shiny changing to bootstrap 3 and lineprof expecting bootstrap 2

**Comment by sanmai-NL** [comment]
What can be done to fix it now? The problem persists for me with both Firefox and Chromium when using a master clone of this morning.

**Comment by hadley** [comment]
Use https://github.com/rstudio/profvis instead
