### ISSUE TITLE
Code junks labeled <Anonymous>

### ISSUE THREAD

**Issue by fdetsch** [hadley/lineprof#35]
In addition to my previous report on [truncated header rows](https://github.com/hadley/lineprof/issues/34) (refer to this issue for reproducible code), I also found that particular code junks were labeled \<Anonymous\> when calling `shine(l)` (see below image). I suspect this is due to explicit `raster::` statements preceding **raster**-related functions, e.g. `raster::brick(...)`, in the [source code of `denoise`](https://github.com/environmentalinformatics-marburg/remote/blob/master/R/denoise.R). Again, any suggestions to fix this, i.e. display `brick` or `raster::brick` rather than \<Anonymous\>?

![truncated_header](http://i.imgur.com/tWOF7J6.png)

**Comment by hadley** [comment]
It's the anonymous function you're calling with `lapply()`

**Comment by fdetsch** [comment]
As far as I can tell, the anonymous function inside `lapply` is not responsible. Just added **Rcpp** functionality to the initial `denoise` function (which is now called [`denoiseC`](https://github.com/environmentalinformatics-marburg/remote/blob/develop/R/denoiseC.R)) and ran the code once again: 

```{r dnsC}
lineprof(denoiseC(vdendool, expl.var = 0.8))

   time alloc release dups           ref                  src
1 0.002 1.425   0.000  907 denoiseC.R#42 denoiseC/princomp   
2 0.003 2.184   2.801  534 denoiseC.R#68 denoiseC/lapply     
3 0.001 0.000   0.000  324 denoiseC.R#76 denoiseC/<Anonymous>
```

Clearly, in line #76, there's `raster::setValues(x, jnk)`, i.e. nothing related to `lapply`. Am I missing something?

**Comment by hadley** [comment]
Which line 76? https://github.com/environmentalinformatics-marburg/remote/blob/master/R/denoise.R#L76

**Comment by fdetsch** [comment]
Here: https://github.com/environmentalinformatics-marburg/remote/blob/develop/R/denoiseC.R

```{r}
rst <- raster::setValues(x, jnk)
```
Isn't the output of `lineprof`
```{r lineprof}
3 0.001 0.000   0.000  324 denoiseC.R#76 denoiseC/<Anonymous>
```
referring to line #76?
